Repository kubeflow/internal-acls, pull requests merged in 2018-12, with the labels that each got.

#29 Added IBM team members for kubeflow.
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#31 Add xieydd to the Kubeflow Member
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#33 Add a member from IBM team
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#35 Add gabrielwen to the Kubeflow team.
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#34 Add Chunhsiang Wang to devrel team members.
  devrel-team.members.txt
Labels: approved, lgtm, size/XS

#32 Add Thea as GitHub Admin.
  github-orgs/OWNERS
  github-orgs/kubeflow/org.yaml
  github-orgs/sync_org.sh
Labels: approved, lgtm, size/M

#36 Add gabrielwen to google-team.members
  google-team.members.txt
Labels: approved, lgtm, size/XS

#38 Adding ashahab to org
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS
