Repository kubeflow/internal-acls, pull requests merged in 2018-11, with the labels that each got.

#18 Update modeldb-team.members.txt
  modeldb-team.members.txt
Labels: approved, lgtm, size/XS

#19 Add Yang to code search team.
  code-search-team.members.txt
Labels: approved, lgtm, size/XS

#20 Checkin config for our GitHub org
  github-orgs/kubeflow/org.yaml
  github-orgs/sync_org.sh
Labels: approved, lgtm, size/L

#21 Add Yang and Thea and Edd.
  devrel-team.members.txt
  google-team.members.txt
  kubeflow-examples-gcr-writers.members.txt
  sync_groups.sh
Labels: approved, lgtm, size/S

#24 Add Yang to ci-team
  ci-team.members.txt
Labels: approved, lgtm, size/XS

#23 Check in IAM policy for kubeflow-examples.
  gcp_iam_policies/README.md
  gcp_iam_policies/kubeflow-examples.iam.policy.yaml
  gcp_iam_policies/update_iam_policy.sh
Labels: approved, lgtm, size/L

#26 Add Argo folks to Kubeflow GitHub org
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#25 * Add aronchick back to the GitHub org.
  OWNERS
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#27 Add Alex from Argo.
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS
