Repository kubeflow/internal-acls, pull requests merged in 2019-01, with the labels that each got.

#40 Add zhenghui@ to google team
  google-team.members.txt
Labels: approved, lgtm, ok-to-test, size/XS

#41 add zhenghui to several groups
  github-orgs/kubeflow/org.yaml
  google-kubeflow-admins.members.txt
  release-team.members.txt
Labels: approved, lgtm, ok-to-test, size/XS

#43 Fix the GitHub org membership.
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#44 Add holden to CI team members
  ci-team.members.txt
Labels: approved, lgtm, needs-ok-to-test, size/XS

#45 Add gabrielwen to admin and release team list.
  google-kubeflow-admins.members.txt
  release-team.members.txt
Labels: approved, lgtm, size/XS

#46 Add Abhilash Pallerlamudi as a member
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#48 Add terrytangyuan to kubeflow org
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#47 Add cc@seldon.io to devrel-team-members.txt
  devrel-team.members.txt
Labels: approved, lgtm, size/XS

#37 Setup permissions on project kf-feast.
  feast-team.members.txt
  gcp_iam_policies/kf-feast.iam.policy.yaml
  sync_groups.sh
Labels: approved, lgtm, size/S

#51 Added svalleru to kubeflow org
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#54 Update google-team.members.txt
  google-kubeflow-admins.members.txt
  google-team.members.txt
  release-team.members.txt
Labels: approved, lgtm, ok-to-test, size/XS

#53 Add eLco as a member
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#52 Adding apverma@google.com (github handle: avdaredevil) to Kubeflow Eng
  github-orgs/kubeflow/org.yaml
  google-kubeflow-admins.members.txt
  google-team.members.txt
  release-team.members.txt
Labels: approved, lgtm, ok-to-test, size/XS
