Repository kubeflow/internal-acls, pull requests merged in 2019-10, with the labels that each got.

#164 Add @astirya as a member.
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#168 Grant viewer only permissions to ci infrastructure.
  ci-team.members.txt
  ci-viewer.members.txt
  gcp_iam_policies/kubeflow-ci-deployment.iam.policy.yaml
  gcp_iam_policies/kubeflow-ci.iam.policy.yaml
  gcp_iam_policies/update_iam_policy.sh
  sync_groups.sh
Labels: approved, lgtm, size/XXL

#170 add xaniasd to org.members
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#169 Add clarketm@ to our CI team so he can help us move our prow instance.
  ci-team.members.txt
Labels: approved, lgtm, size/XS

#172 add swiftdiaries to Cisco team, kanban
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#173 Update ci-viewer.members.txt
  ci-viewer.members.txt
Labels: approved, lgtm, size/XS

#174 Include me as viewer
  ci-viewer.members.txt
Labels: approved, lgtm, needs-ok-to-test, size/XS

#176 add ryandawsonuk
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#171 Add myself to google-team members
  google-team.members.txt
Labels: approved, lgtm, needs-ok-to-test, size/XS

#177 adding swiftdiaries to CI
  ci-viewer.members.txt
Labels: approved, lgtm, size/XS

#178 Add janeman98 to kubeflow org
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#181 Update ci-viewer members
  ci-viewer.members.txt
Labels: approved, lgtm, needs-ok-to-test, size/XS

#180 update ci-viewer team to get pods log
  gcp_iam_policies/kubeflow-ci-deployment.iam.policy.yaml
  gcp_iam_policies/kubeflow-ci.iam.policy.yaml
Labels: approved, lgtm, size/XS

#182 Add teams for xgboost-operator, mpi-operator, and kubeflow/common
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/S

#184 Add kwasi to Kubeflow org
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#185 Add pugangxa from IBM
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, ok-to-test, size/XS
