Repository kubeflow/internal-acls, pull requests merged in 2019-07, with the labels that each got.

#114 Added Chun-Hsiang Wang as an org member.
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#115 Adds krishnadurai to kubeflow org
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#117 Added @wuchunghsuan as an org member
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#118 Adds thedriftofwords to the org
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#120 Update org.yaml
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#119 Add Bobgy to org.yaml
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#122 Remove inactive members
  release-team.members.txt
Labels: approved, lgtm, size/XS

#124 Add zhenghuiwang to release-team
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#126 Add scottilee to Kubeflow members
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#125 Create an issue template for joining the Kubeflow GitHub org.
  .github/ISSUE_TEMPLATE/join_org.md
  .github/stale.yml
  github-orgs/README.md
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/M

#123 Add membership for jxzheng@
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#127 Remove vicaire as an admin
  github-orgs/sync_org.sh
Labels: approved, lgtm, size/XS

#128 cleanup memberships for vicaire
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#121 Grant example maintainers access to clusters in kubeflow-ci-deployment.
  create_group.sh
  example-maintainers.members.txt
  gcp_iam_policies/kubeflow-ci-deployment.iam.policy.yaml
  sync_groups.sh
Labels: approved, lgtm, size/XL
