Repository kubeflow/internal-acls, pull requests merged in 2019-02, with the labels that each got.

#55 Fix the github org file.
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#57 Sync github-team@kubeflow.org to source repo.
  github-team.members.txt
  sync_groups.sh
Labels: approved, lgtm, size/S

#56 Add kimwnasptd to github org
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#58 Fix org.
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#60 Update org.yaml to add zabbasi
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#62 Add rpasricha to org.yaml
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#61 Add bikramnehra to Kubeflow org
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#64 Adding achalshant
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#65 Update modeldb-team.members.txt
  modeldb-team.members.txt
Labels: approved, lgtm, size/XS
