Repository kubeflow/internal-acls, pull requests merged in 2019-09, with the labels that each got.

#144 Added Elvira to project-maintainers group
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#146 Add Google Kubeflow engineering team to project-maintainers so they can have
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/S

#143 Update org.yaml
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/S

#142 Add james-jwu to org.yaml
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#147 Create a google group for people who will setup KCC for Kubeflow.
  kf-kcc-admins.members.txt
  sync_groups.sh
Labels: approved, lgtm, size/S

#145 Added the rest of PM team
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#149 Fixed broken org.yaml due to missing entries in org members. Added manual test.
  README.md
  github-orgs/kubeflow/org.yaml
  github-orgs/test_org_yaml.py
Labels: approved, lgtm, size/M

#152 Added cspavlou to kubeflow members.
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#150 Update project maintainers group
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#155 Remove nonexistent user rem20806
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#156 Added rebeccamcfadden to Kubeflow org
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#160 Add a member from IBM team
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#161 Add pdmack to project-maintainers
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#158 add kkasravi to release-team
  release-team.members.txt
Labels: approved, lgtm, size/XS

#162 Please add Tabrizian into Kubeflow org as GitHub member
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS
