Repository kubeflow/internal-acls, pull requests merged in 2019-04, with the labels that each got.

#79 Update sync_org.sh to provide commands to dump the org.
  github-orgs/kubeflow/org.yaml
  github-orgs/sync_org.sh
Labels: approved, lgtm, size/M

#74 add kam to ci-team.members.txt
  ci-team.members.txt
Labels: approved, lgtm, size/XS

#77 Add KingOnTheStar to kubeflow.member, he is working on mxnet-operator
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#81 Add yanniszark to Kubeflow org
  devrel-team.members.txt
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#80 added self to google-team.members.txt
  github-orgs/kubeflow/org.yaml
  google-team.members.txt
Labels: approved, lgtm, ok-to-test, size/XS

#82 Adding Verta GitHub username for Manasi (working on ModelDB / metadata)
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#84 Add jingzhang36 as kubeflow team member.
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#85 Updated permissions
  github-orgs/kubeflow/org.yaml
  google-team.members.txt
Labels: size/XS

#87 Add prodonjs@ to Google Admins
  google-kubeflow-admins.members.txt
Labels: approved, lgtm, size/XS

#86 Add Jiaxin Shan(Jeffwan@) to org
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#88 Add Wei Yan(@ywskycn) to org and update related company team
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/S

#89 Add rlenferink to kubeflow org
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#92 Adding Ebi(ashahba) to ci-team members
  ci-team.members.txt
Labels: approved, lgtm, size/XS
