Repository kubeflow/internal-acls, pull requests merged in 2019-12, with the labels that each got.

#193 Add the prow bot for the google repo to ci team.
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#196 Add myself in the org.yaml
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#198 Add fenglixa from IBM
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, ok-to-test, size/XS
