Repository kubeflow/internal-acls, pull requests merged in 2019-03, with the labels that each got.

#66 Add Dan Sanche as DevRel contributor
  devrel-team.members.txt
Labels: approved, lgtm, needs-ok-to-test, size/XS

#63 Add prodonjs to org.yaml as member of Google
  github-orgs/kubeflow/org.yaml
  google-team.members.txt
  release-team.members.txt
Labels: approved, lgtm, needs-ok-to-test, size/XS

#68 Update org.yaml
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#69 Add Arrikto folks
  devrel-team.members.txt
Labels: approved, lgtm, size/XS

#73 Added Elvira Dzhuraeva to Kubeflow members list
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#75 Make it easy to fetch and sync IAM policies.
  gcp_iam_policies/README.md
  gcp_iam_policies/devstats.iam.policy.yaml
  gcp_iam_policies/github-codenet.iam.policy.yaml
  gcp_iam_policies/github-probots.iam.policy.yaml
  gcp_iam_policies/kf-modeldb-dev.iam.policy.yaml
  gcp_iam_policies/kubeflow-ci.iam.policy.yaml
  gcp_iam_policies/kubeflow-devstats.iam.policy.yaml
  gcp_iam_policies/update_iam_policy.sh
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XXL
