Repository kubeflow/internal-acls, pull requests merged in 2020-12, with the labels that each got.

#412 added xiyue as member, fixed test_org_yaml.py
  .gitignore
  github-orgs/kubeflow/org.yaml
  github-orgs/test_org_yaml.py
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/S

#411 Adding nachocano as a new member
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#413 Update ci-team.yaml
  google_groups/groups/ci-team.yaml
Labels: approved, cla: yes, size/XS

#415 Add rui5i to pipeline team
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, size/XS

#414 Add adriangonz to Kubeflow org
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#418 test: add google-oss-robot as admin
  github-orgs/kubeflow/org.yaml
  github-orgs/manifests/validate_config.py
Labels: approved, cla: yes, lgtm, size/XS

#417 Update wg-notebooks leads
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, size/XS

#416 Jeffwan@ step down and nominate PatrickXYS@ to represent AWS
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, size/XS

#421 Add zijianjoy (jamxl) to Kubeflow.org, Google and ci-team members, fixed instruction in README
  README.md
  github-orgs/kubeflow/org.yaml
  google_groups/groups/ci-team.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#422 Add evan-hataishi to Kubeflow org
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#423 Add jamesjwu@google.com to ci-team.yaml
  google_groups/groups/ci-team.yaml
Labels: approved, cla: yes, lgtm, size/XS

#420 wg-notebooks: Rename group to wg-notebooks-leads
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, size/XS
