Repository kubeflow/internal-acls, pull requests merged in 2020-07, with the labels that each got.

#274 Add jasonliu747 as kubeflow org member
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#276 Add harshad16 to kubeflow ci-team
  ci-team.members.txt
Labels: approved, lgtm, needs-ok-to-test, size/XS

#281 Update org.yaml
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#280 Adding chesu@ and gongyuan@ to google-team.members
  google-team.members.txt
Labels: approved, lgtm, size/XS

#283 Update org.yaml
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/S

#284 Update org.yaml
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#286 Fix the yaml #285.
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#287 Update the issue template to include running the tests.
  .github/ISSUE_TEMPLATE/join_org.md
Labels: approved, lgtm, size/S

#290 Add scottilee to ci team
  ci-team.members.txt
Labels: approved, lgtm, size/XS

#291 Add in alexlatchford to Kubeflow contributors
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#277 Create calendar-admins.members.txt
  calendar-admins.members.txt
Labels: approved, lgtm, needs-ok-to-test, size/XS

#292 Adding member to github org
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#293 add Qingshan Chen as Kubeflow member
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#296 Add StefanoFioravanzo to Kubeflow org
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#298 Created a team for kfserving maintainers
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/S

#299 Update org.yaml
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#300 Update org.yaml
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#301 ci-bots need access to repository kubeflow/blog
  github-orgs/__pycache__/test_org_yaml.cpython-38-pytest-5.4.3.pyc
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#302 Update org.yaml
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#303 Update org.yaml
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS
