Repository kubeflow/internal-acls, pull requests merged in 2020-08, with the labels that each got.

#297 Update org.yaml to add SUSE team members contributing to Kubeflow
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#304 Create the calendar admins group.
  calendar-admins.members.txt
  sync_groups.sh
Labels: approved, lgtm, size/XS

#305 Adding ilan filonenko (ifilonenko) as a member
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#307 Document how to set up GAM
  README.md
Labels: approved, lgtm, size/XS

#306 adds swiftdiaries [Adhita] to the release team
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#309 Update pipelines team
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#308 Add k8s-ci-robot as Kubeflow admin
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#311 Update Kubeflow org admin
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#312 Adding James to google-kubeflow-admins.members.txt
  google-kubeflow-admins.members.txt
Labels: approved, lgtm, size/XS

#313 Update org.yaml
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#314 Update org.yaml - remove bobgy, james-jwu, k8s-ci-robot, rmgogogo from org members
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#315 Adding RFMVasconcelos to org.yaml
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#310 Fix test_org_yaml.py
  github-orgs/test_org_yaml.py
Labels: approved, lgtm, size/XS

#318 Add AutoML and Training WG teams
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/M

#322 Remove Googlers no longer maintaining kf-kcc infra.
  kf-kcc-admins.members.txt
Labels: approved, lgtm, size/XS

#324 Add Jiaxin(jeffwan@) to kf-kcc members
  kf-kcc-admins.members.txt
Labels: approved, lgtm, size/XS

#325 Add @andreyvelich to kf-kcc members
  kf-kcc-admins.members.txt
Labels: approved, lgtm, size/XS

#326 Add "wg-" prefix to the leads mailing lists.
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/M

#327 add thesuperzapper to org
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#328 Add Dan Sun to the ci member list
  ci-team.members.txt
Labels: approved, lgtm, size/S

#316 Adding nakfour from redhat to org
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#321 add new community meeting hosts
  community-meeting-hosts.members.txt
  drive-content-managers.members.txt
  sync_groups.sh
Labels: approved, lgtm, ok-to-test, size/M

#333 Adds Karthik (karkumar) to Kubeflow org
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#330 Azure contributors
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, needs-ok-to-test, size/S
