Repository kubeflow/internal-acls, pull requests merged in 2020-03, with the labels that each got.

#210 add weiqiang as a kubeflow org member
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#215 Add yuzliu to the org
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#217 add drive-content-manager file
  drive-content-managers.members.txt
Labels: approved, lgtm, needs-ok-to-test, size/XS

#219 Move current content managers into the new drive-content-managers group.
  drive-content-managers.members.txt
  google-codelab-projects-owners.members.txt
  sync_groups.sh
Labels: approved, lgtm, size/S

#221 Request ci-viewer.members.txt permission
  ci-viewer.members.txt
Labels: approved, lgtm, size/XS

#222 Remove dakoner from kubeflow github org.
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#223 add ckadner to Kubeflow org
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#224 Add crobby to kubeflow org as a member
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#226 Add chesu@ to drive-content-managers.members.txt
  drive-content-managers.members.txt
Labels: approved, lgtm, size/XS

#227 Add clarketm as kubeflow org member
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS
