Repository kubeflow/internal-acls, pull requests merged in 2020-06, with the labels that each got.

#256 Add LaynePeng as kubeflow org members for fate-operator project
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#257 chore: Remove outdated members and add fate to cibots
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#259 Add @woop to Kubeflow org
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#260 Create Katib release team
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#258 Add jiahaoc1993 as kubeflow org member
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#262 add kfctl-release team
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#263 Add Fairing release team
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#255 Add pingsutw to Kubeflow org
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#264 Update OWNERs file.
  OWNERS
Labels: approved, lgtm, size/XS

#265 Self nominate to join the org to be able to trigger test
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#266 Add myself to release team members
  release-team.members.txt
Labels: approved, lgtm, size/XS

#267 adding lalith vaka to the kubeflow org
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#268 Update org.yaml
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#269 Update org.yaml
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#270 Add Bobgy to kubeflow ci-team
  ci-team.members.txt
  ci-viewer.members.txt
Labels: approved, lgtm, size/XS

#271 Add Bobgy to google-kubeflow-admins
  google-kubeflow-admins.members.txt
Labels: approved, lgtm, size/S

#272 Rename Ant Financial to Ant Group
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS
