Repository kubeflow/internal-acls, pull requests merged in 2020-02, with the labels that each got.

#192 add yeya24 to org member
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#195 add axsaucedo at seldon to members
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#206 Add fediazgon to org.yaml
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#205 Add Realsen to contributors.
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#207 Update org.yaml
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#208 Add myself to kubeflow org
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#209 Add eterna2 to kubeflow member
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, ok-to-test, size/XS
