Repository kubeflow/internal-acls, pull requests merged in 2020-11, with the labels that each got.

#369 Randomized team name to fix issue
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, size/XS

#370 Add @cvenets as an org member
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, size/XS

#364 PSG transition: jlewi -> bobgy
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, size/XS

#372 Move the K8s manifests for github sync into internal-acls.
  github-orgs/manifests/Makefile
  github-orgs/manifests/README.md
  github-orgs/manifests/github-sync-cron-job.yaml
  github-orgs/manifests/github-sync-job.yaml
  github-orgs/manifests/validate_config.py
Labels: approved, cla: yes, lgtm, size/L

#371 Add third-party-bots with caffe2-operator access
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, size/XS

#373 Add kfctl repo into third-party-bots
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, size/XS

#374 Add kfserving repo into third-party-bots
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, size/XS

#377 Add kfctl repo into third-party-bots
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, size/XS

#378 Add the rest of repos into third-party-bots
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, size/XS

#376 Refresh the GitHub org admins.
  github-orgs/kubeflow/org.yaml
  github-orgs/manifests/github-sync-cron-job.yaml
  github-orgs/manifests/github-sync-job.yaml
  github-orgs/manifests/validate_config.py
Labels: approved, cla: yes, lgtm, size/S

#379 Adding yilun-msft to the members
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#380 Remove temp admin access from PatrickXYS
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, size/XS

#383 Add PatrickXYS as ci-viewer
  google_groups/groups/ci-viewer.yaml
Labels: approved, cla: yes, lgtm, size/XS

#382 Add WG Deployment and Manifests
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, size/S

#381 Adding Microsoft Azure Owners
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, size/XS

#385 fix: update kubeflow admin config. Fixes #384
  github-orgs/kubeflow/org.yaml
  github-orgs/manifests/validate_config.py
  github-orgs/sync_org.sh
Labels: approved, cla: yes, lgtm, size/S

#388 chore: use Bobgy's github token instead. Fixes #387
  github-orgs/manifests/README.md
  github-orgs/manifests/github-sync-cron-job.yaml
  github-orgs/manifests/github-sync-job.yaml
Labels: approved, cla: yes, size/S

#389 chore: move jlewi to member
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, size/XS

#386 doc: update github sync deploy instructions
  github-orgs/manifests/Makefile
  github-orgs/manifests/README.md
Labels: approved, cla: yes, lgtm, size/M

#394 Create a kubeflow/code-intelligence team
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, size/XS

#393 Add PatrickXYS as kubeflow-testing team member
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, size/XS

#395 Permissions for v1.1-branch cut
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, size/XS

#397 Change ci viewer email
  google_groups/groups/ci-viewer.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#398 remove myself from repo owner so that bob can be well routed.
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#399 add @moficodes to Kubeflow org
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, size/XS

#400 doc: join github org instructions in README.md
  README.md
Labels: approved, cla: yes, lgtm, size/S

#401 github-orgs: Add Arrikto team
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, size/S

#402 Add mbaijal to Kubeflow org
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, size/XS

#406 Add jeremy to ci-team so I can debug ACM sync issues related to label-bot-clusters
  google_groups/groups/ci-team.yaml
Labels: approved, cla: yes, lgtm, size/XS

#408 doc: Updated wording of readme.md
  README.md
Labels: approved, cla: yes, lgtm, size/S

#404 Remove deprecated github teams
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, size/M

#409 Update org.yaml
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#407 Add mbaijal to AWS org
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, size/XS
