Repository kubeflow/internal-acls, pull requests merged in 2020-09, with the labels that each got.

#334 Add @pyalex to kubeflow org.yaml
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#329 Add @andreyvelich to kubeflow-ci members
  ci-team.members.txt
Labels: approved, lgtm, size/XS

#335 Add kf-kcc GitHub team
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/S

#319 Adding MartinForReal as org members.
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#323 Add Yuzhui as admin members
  kf-kcc-admins.members.txt
Labels: approved, lgtm, size/XS

#317 Add knkski to org.yaml
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#339 Update org.yaml
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#320 add deadeyegoodwin to org
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#336 Add salanki as member
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#341 Define an admins group so its easy to ping relevant folks.
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#342 Add @kevinstumpf to kubeflow org.yaml
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#343 Add @jrykr to kubeflow org.
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#345 Remove 'karkumar' from org.yaml
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, size/XS

#332 add b675987273 to org.yaml
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS
