Repository kubeflow/internal-acls, pull requests merged in 2020-10, with the labels that each got.

#350 add theofpa as github-org member
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#352 Add pvaneck as member
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#355 Define pipeline leads and project steering groups.
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, size/S

#353 Add aws-kf-ci-bot into the list
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, size/XS

#358 create wg-notebook-leads group
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, size/XS

#360 Update org.yaml
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, size/XS

#357 Grant PatrickXYS Temporary Admin Access to katib and pytorch repos
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, size/XS

#356 add user subodh101 as ci viewer and org member
  github-orgs/kubeflow/org.yaml
  google_groups/ci-viewer.members.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#363 Grant aws-kf-ci-bot write access to kfserving
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, size/XS

#368 Add subodh101 as ci viewer
  google_groups/groups/ci-viewer.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS
