Repository kubeflow/internal-acls, pull requests merged in 2020-05, with the labels that each got.

#240 add andrew and kevin to kubeflow org
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#241 Changes github name for Ellis
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#242 Add @Jeffwan to ci-team members
  ci-team.members.txt
Labels: approved, lgtm, size/XS

#244 Add Jinchi from IBM ci team to fix test problems
  ci-team.members.txt
Labels: approved, lgtm, size/XS

#243 Add surajkota RedbackThomson akartsky to Kubeflow org
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#245 Adds ian coffey to test infra team list
  ci-viewer.members.txt
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#247 Add myself to release team
  github-orgs/kubeflow/org.yaml
  release-team.members.txt
Labels: approved, lgtm, size/XS

#250 Update github config with latest team permissions
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XL

#251 Specify repos for operator teams and add mxnet-operator team
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/S

#252 Add back members from Ant Financial that went missing
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#246 Add AWS team and add Jeffwan to project-maintainers
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/S

#253 Updated org.yaml to add me as member
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#254 Add vpavlin as a member of Kubeflow
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS
