Repository kubeflow/internal-acls, pull requests merged in 2021-09, with the labels that each got.

#491 Update drive-content-managers.yaml
  google_groups/groups/drive-content-managers.yaml
Labels: approved, lgtm, size/XS

#494 Add Yuki to member list
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS, cla: yes

#492 Add `judahrand` to member list
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS, ok-to-test, cla: yes

#497 Add FPGA OWNERS to member list
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS, cla: yes
