Repository kubeflow/internal-acls, pull requests merged in 2021-07, with the labels that each got.

#470 Added name/email to .yaml files
  github-orgs/kubeflow/org.yaml
  google_groups/groups/ci-team.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#471 Add NikeNano as member of ci-team.
  google_groups/groups/ci-team.yaml
Labels: approved, cla: yes, lgtm, size/XS

#472 Add shannonbradshaw to members list.
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#473 Add alculquicondor to members
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#477 Add Malini to release team
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, size/XS

#478 Update list of members from Ant Group
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, size/XS

#479 rm rmgogogo who left Google
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, size/XS

#481 Add Jose-Matsuda to member list
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#480 Add wg102 to member list
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS
