Repository kubeflow/internal-acls, pull requests merged in 2021-10, with the labels that each got.

#496 Add `judahrand` to `ci-viewer` group
  google_groups/groups/ci-viewer.yaml
Labels: approved, lgtm, size/XS, cla: yes

#498 Fix typo in my email
  google_groups/groups/ci-viewer.yaml
Labels: approved, lgtm, size/XS, cla: yes

#499 Swap TF to Training operator
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/S, cla: yes

#500 Remove KFServing from org.yaml
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/M, cla: yes

#501 Add goswamig to the member list
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS, needs-ok-to-test, cla: yes
