Repository kubeflow/internal-acls, pull requests merged in 2021-12, with the labels that each got.

#513 Add hackerboy01 to the member list
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS, ok-to-test, cla: yes

#512 Add DnPlas to member list
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS, ok-to-test, cla: yes

#502 add jlbutler to member list
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS, needs-ok-to-test, cla: yes

#518 add denkensk as member
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS, needs-ok-to-test
