Repository kubeflow/internal-acls, pull requests merged in 2021-04, with the labels that each got.

#448 add shinytang6 to kubeflow member
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#447 add evilnick to members
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#449 Adding members to Azure Team
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, size/XS

#451 add zw0610 to kubeflow member
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#450 Include AnyISalIn as a member
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#453 Add KFP SDK team to ACL file for CI
  google_groups/groups/ci-team.yaml
Labels: approved, cla: yes, lgtm, size/XS

#455 add yhwang as KF member
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, size/XS

#454 Include tasos-ale as a member
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#458 Update google team in org.yaml
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, size/S

#456 add Arhell as KF member
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#457 Add tedhtchang as a member
  github-orgs/kubeflow/org.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS
