Repository kubeflow/internal-acls, pull requests merged in 2022-06, with the labels that each got.

#547 Update org.yaml
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS, ok-to-test

#545 Update release members and manager
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#549 modify org.yaml
  github-orgs/kubeflow/org.yaml
  google_groups/groups/ci-team.yaml
Labels: approved, lgtm, size/XS, needs-ok-to-test

#554 Add gkcalat to the ci-team@kubeflow.org
  google_groups/groups/ci-team.yaml
Labels: approved, lgtm, size/XS, needs-ok-to-test

#555 Add gkcalat to Kubeflow org ACL
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS, needs-ok-to-test

#552 add Garrybest to members list
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS, needs-ok-to-test

#553 Add alembiewski to the members list
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS, ok-to-test
