Repository kubeflow/internal-acls, pull requests merged in 2022-01, with the labels that each got.

#519 Add toshi-k to members list.
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS, needs-ok-to-test

#520 remove ChanYiLin from wg-training-leads
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#522 Create examples team
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#523 Update owners
  OWNERS
Labels: approved, lgtm, size/XS

#517 Create release-managers GitHub team
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#511 Update github release team with 1.5 members
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/M, cla: yes

#516 Cleanup GitHub org file
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/L

#524 Transition of Bobgy
  OWNERS
  gcp_iam_policies/OWNERS
  github-orgs/OWNERS
  github-orgs/kubeflow/org.yaml
  github-orgs/manifests/github-sync-cron-job.yaml
  github-orgs/manifests/github-sync-job.yaml
  github-orgs/sync_org.sh
Labels: approved, lgtm, size/S

#525 chore: Use zijianjoy's github token instead
  github-orgs/manifests/README.md
  github-orgs/manifests/github-sync-cron-job.yaml
  github-orgs/manifests/github-sync-job.yaml
Labels: approved, lgtm, size/S

#526 chore: remove Bobgy from admins
  github-orgs/kubeflow/org.yaml
  github-orgs/manifests/README.md
  github-orgs/manifests/validate_config.py
Labels: approved, lgtm, size/XS
