Repository kubeflow/internal-acls, pull requests merged in 2023-01, with the labels that each got.

#581 Add lehrig to the Member List
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS, needs-ok-to-test

#576 Update Release Team for 1.7
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#579 Add yubozhao to member in the org.yaml
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS, needs-ok-to-test

#588 Remove frederick0329 from the org to unblock sync. Fixes #587
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#589 Remove gcp-blueprints as the repo was deleted. Part of #587
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#590 chore: update peribolos image
  github-orgs/manifests/github-sync-cron-job.yaml
  github-orgs/manifests/github-sync-job.yaml
Labels: approved, lgtm, size/XS

#591 chore: fix invalid makefile target reference in README.md
  github-orgs/manifests/README.md
Labels: approved, lgtm
