Repository kubeflow/internal-acls, pull requests merged in 2024-03, with the labels that each got.

#659 Add diegolovison as member to kubeflow org
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS, needs-ok-to-test

#661 Fix visibility of KSC team. Fixes #660
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#663 Add JosepSampe, revit13, and roytman to Kubeflow org
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#664 Update list of active IBM members
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#662 Update Red Hat team members
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/S

#665 Add distribution maintainers from VMware
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS, needs-ok-to-test

#667 Add Spark Operator Maintainers
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS
