Repository kubeflow/internal-acls, pull requests merged in 2024-08, with the labels that each got.

#694 chore: Attempt to remove google-admin from admin role of kubeflow org.
  github-orgs/kubeflow/org.yaml
  github-orgs/manifests/github-sync-cron-job.yaml
  github-orgs/manifests/github-sync-job.yaml
  github-orgs/manifests/validate_config.py
  github-orgs/sync_org.sh
Labels: approved, lgtm, size/XS

#696 Add ouadakarim to kubeflow org
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS, needs-ok-to-test

#699 Add paulinapk@ to Kubeflow CI
  google_groups/groups/ci-team.yaml
Labels: approved, lgtm, size/XS, needs-ok-to-test

#698 Add ElayAharoni as member to kubeflow-org
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS, ok-to-test

#700 Add alexcreasy as member
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#702 Add jacobsalway as member
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS, ok-to-test

#701 chore: Add Kubeflow Steering Committee members to the org admin role.
  github-orgs/kubeflow/org.yaml
  github-orgs/manifests/validate_config.py
Labels: approved, lgtm, size/S
