Repository kubeflow/internal-acls, pull requests merged in 2024-06, with the labels that each got.

#683 Add helenxie-bit as member
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS, needs-ok-to-test

#685 add gregsheremeta to kubeflow team and Red Hat org
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS, ok-to-test

#684 Add milosjava as member
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS, needs-ok-to-test

#686 Add `jiridanek` as member and to Red Hat team
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS
