Repository kubeflow/internal-acls, pull requests merged in 2024-04, with the labels that each got.

#669 Add Electronic-Waste as member.
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS, ok-to-test

#670 Add rafalbigaj to kubeflow org
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#671 Add Data WG Team
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#672 Add gmfrasca as member to kubeflow org
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS, needs-ok-to-test

#674 Add gmfrasca to Red Hat team
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#618 add write access to `kubeflow` repo for `wg-notebooks-leads`
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#641 Add rawc0der as member
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS, ok-to-test

#676 fix: Remove non-exist members
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS
