Repository kubeflow/internal-acls, pull requests merged in 2024-01, with the labels that each got.

#630 Add DharmitD as member
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS, needs-ok-to-test

#631 Add kromanow94 as member
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS, needs-ok-to-test

#632 fix: use batch/v1 for Cronjob.
  github-orgs/manifests/github-sync-cron-job.yaml
Labels: approved, lgtm, size/XS

#633 fix: Remove rfmvasconcelos since this handle doesn't exist any more.
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/M

#634 Revert "fix: Remove rfmvasconcelos since this handle doesn't exist an…
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/M

#635 fix: Remove rfmvasconcelos again.
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#642 Adding WG-Data and their owners
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS, needs-ok-to-test

#643 Add model-registry write permission to point-of-interest.
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#645 Add deepanker13 to Kubeflow org
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#646 chore: Adding CNCF owners to be member and owner of Kubeflow
  github-orgs/kubeflow/org.yaml
  github-orgs/manifests/validate_config.py
Labels: approved, lgtm, size/XS

#647 chore: remove duplicate member and owner.
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#644 Assemble release team for 1.9
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/S

#648 add tarilabs as member
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS, needs-ok-to-test

#637 Add HumairAK as member to kubeflow org.
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS, ok-to-test
