Repository kubeflow/internal-acls, pull requests merged in 2024-09, with the labels that each got.

#704 fix: Deduplicate Kubeflow steering committee member in the member field
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#705 Add `kubeflow/dashboard` repo
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#703 Add dpoulopoulos as member
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS, ok-to-test

#712 Add YosiElias as member to kubeflow org
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS, needs-ok-to-test

#707 adding tarekabouzeid to kubeflow org
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS, needs-ok-to-test
