Repository kubeflow/internal-acls, pull requests merged in 2025-02, with the labels that each got.

#739 Updating OWNERS for 2025 KSC members
  OWNERS
Labels: approved, size/XS

#740 Updating OWNERS to emeritus_approvers
  OWNERS
Labels: approved, lgtm, size/XS

#737 fix: improved membership request template
  .github/ISSUE_TEMPLATE/join_org.md
Labels: approved, lgtm, size/M, needs-ok-to-test

#743 fix: Remove @haozheng95 from the Kubeflow GitHub org
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#746 fix: Remove @marload from the Kubeflow GitHub
  github-orgs/kubeflow/org.yaml
Labels: size/XS

#748 fix: Remove @prodonjs from the Kubeflow GitHub
  github-orgs/kubeflow/org.yaml
Labels: lgtm, size/XS

#741 Rename kubeflow/training-operator to kubeflow/trainer
  github-orgs/kubeflow/org.yaml
Labels: approved, size/S

#742 Add astefanutti as member of Kubeflow org
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS, ok-to-test

#738 chore: add myself to members org
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS, needs-ok-to-test

#751 Add mahdi khashan as a member
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS, ok-to-test

#752 Remove @franciscojavierarceo and @juliusvonkohout from org members
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#756 Add chasecadet as member
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS, needs-ok-to-test

#757 chore: add myself to members org
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS, needs-ok-to-test
