Repository kubeflow/internal-acls, pull requests merged in 2025-06, with the labels that each got.

#792 Add @andyatmiami as Member of Kubeflow org
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#793 add Al-Pragliola to model-registry Maintainers
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#794 Add kramaranya to Kubeflow members
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS, needs-ok-to-test

#797 Adding stale bot workflow
  .github/workflows/stale.yml
Labels: approved, lgtm, size/M

#800 Add BieniekAlexander to Kubeflow members
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS, needs-ok-to-test
