Repository kubeflow/internal-acls, pull requests merged in 2025-09, with the labels that each got.

#825 Create Kubeflow SDK team
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/S

#833 add jonburdo as member
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS, needs-ok-to-test

#834 add `read` permission to `kubeflow-notebooks-security` team
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#848 add @ederign to wg-data-leads
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS
