Repository kubeflow/internal-acls, pull requests merged in 2025-07, with the labels that each got.

#805 REQUEST: Add @rudeigerc as Member
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#796 Add @yehudit1987 as a member
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS, needs-ok-to-test

#806 chore: Add `docs-agent` repository
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#809 Add GSoC contributors to Kubeflow members list
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS, needs-ok-to-test

#808 Update KFP Maintainers team
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/M

#810 Update wg-pipelines-leads permissions
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#812 Add Kubeflow SDK Contributors to Kubeflow GitHub Org
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#811 Remove company teams
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/L

#814 REQUEST: Add @nsingla to the members list
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS, needs-ok-to-test
