Repository kubeflow/internal-acls, pull requests merged in 2025-04, with the labels that each got.

#765 add adysenrothman to org member list
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS, ok-to-test

#769 Add Crazyglue as kubeflow member
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS, needs-ok-to-test

#766 Create GitHub Team for Kubeflow Trainer Maintainers
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS

#770 add @milinddethe15 as org member
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS, ok-to-test

#773 Add Kubeflow SDK repository
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS
