Repository kubeflow/internal-acls, pull requests merged in 2025-08, with the labels that each got.

#815 Add pschoen-itsc to members
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS, needs-ok-to-test

#816 Partially revert "Remove company teams"
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/L

#817 Remove more Kubeflow GitHub teams
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/M

#818 Remove more Kubeflow GitHub teams
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/M

#819 Remove more Kubeflow GitHub teams
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/M

#821 Add mturley as member
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS, needs-ok-to-test

#823 add: add jaiakash to kubeflow github org
  github-orgs/kubeflow/org.yaml
Labels: approved, lgtm, size/XS, needs-ok-to-test
